name: Build APK

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}

      - name: Configure Keystore
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" > keystore.pfx.asc
          gpg -d --passphrase "${{ secrets.KEYSTORE_PASSPHRASE }}" --batch keystore.pfx.asc > app/keystore.pfx
          echo "storeFile=keystore.pfx" >> local.properties
          echo "storePassword=${{ secrets.KEYSTORE_STORE_PASSWORD }}" >> local.properties
          echo "keyAlias=${{ secrets.KEYSTORE_KEY_ALIAS }}" >> local.properties
          echo "keyPassword=${{ secrets.KEYSTORE_KEY_PASSWORD }}" >> local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          path: app/build/outputs/apk/release/app-release.apk
          retention-days: 1
